---
- name: playbook
  hosts: all
  become: yes
  
  tasks: 
    - name: httpd installation
      yum: 
        name: httpd
        state: present
        
    - name: firewalld stop
      service: 
        name: firewalld
        state: stopped
        enabled: false
        
    - name: httpd start and enable
      service: 
        name: httpd
        state: started
        enabled: true

    - name: index.html create
      get_url: url=https://www.nginx.com dest=/var/www/html
